name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

concurrency:
  group: nightly-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-test-eval-text-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for text models
        timeout-minutes: 120
        run: |
          cd test/srt
          python3 test_nightly_text_models_gsm8k_eval.py

  nightly-test-perf-text-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh


      - name: Run performance test for text models
        timeout-minutes: 180
        env:
          TRACE_BASE_URL: https://github.com/sgl-project/ci-data/traces/${{ github.run_id }}
          PERFETTO_RELAY_URL: ${{ vars.PERFETTO_RELAY_URL }}
        run: |
          rm -rf test/srt/performance_profiles_text_models/
          cd test/srt
          python3 test_nightly_text_models_perf.py

      - name: Publish traces to storage repo
        env:
          GH_PAT_FOR_DOCUMENTATION: ${{ secrets.GH_PAT_FOR_DOCUMENTATION }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          python3 scripts/ci/publish_traces.py

  nightly-test-eval-vlm-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run eval test for VLM models (fixed MMMU-100)
        timeout-minutes: 240
        run: |
          cd test/srt
          python3 test_nightly_vlms_mmmu_eval.py


  nightly-test-perf-vlm-models:
    if: github.repository == 'sgl-project/sglang'
    runs-on: 1-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash scripts/ci/ci_install_dependency.sh

      - name: Run perf test for VLM models (MMMU)
        timeout-minutes: 240
        env:
          TRACE_BASE_URL: https://raw.githubusercontent.com/mickqian/SGLang-test-nightly/main/traces/${{ github.run_id }}
          PERFETTO_RELAY_URL: ${{ vars.PERFETTO_RELAY_URL }}
        run: |
          pwd
          rm -rf test/srt/performance_profiles_vlms/
          python3 test/srt/test_nightly_vlms_perf.py

      - name: Publish traces to storage repo
        env:
          GH_PAT_FOR_DOCUMENTATION: ${{ secrets.TMP_NIGHTLY_CI_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          pwd
          python3 scripts/ci/publish_traces.py --vlm
